services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\HappinessBundle\:
        resource: '../../*'
        exclude:
            - '../../DependencyInjection/'
            - '../../Reporting/'
            - '../../Resources/'
            - '../../tests/'
            - '../../Tests/'
